name: Build and Deploy
on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: azure
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure required Azure resouces
        run: ${{ github.workspace }}/scripts/action-pre-build.sh -r ${{ vars.RESOURCE_GROUP }} -c ${{ vars.CONTAINER_REGISTRY_NAME }}

      - name: Collect Client credentials for Container Registry
        run: |
          REGISTRY_USERNAME=$(echo $AZURE_CREDENTIALS | jq -r '.["clientId"]')
          REGISTRY_PASSWORD=$(echo $AZURE_CREDENTIALS | jq -r '.["clientSecret"]')
          echo "::add-mask::$REGISTRY_USERNAME"
          echo "::add-mask::$REGISTRY_PASSWORD"
          echo REGISTRY_USERNAME=$REGISTRY_USERNAME >> $GITHUB_ENV
          echo REGISTRY_PASSWORD=$REGISTRY_PASSWORD >> $GITHUB_ENV
    
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io
          acrUsername: ${{ env.REGISTRY_USERNAME }}
          acrPassword: ${{ env.REGISTRY_PASSWORD }}
          containerAppName: ${{ vars.CONTAINER_APP_NAME }}
          resourceGroup: ${{ vars.RESOURCE_GROUP }}
          location: ${{ vars.LOCATION }}
